---
- name: configure an openwrt system
  hosts: openwrt
  user: root
  gather_facts: no
  roles:
    - openwrt-system
    - openwrt-wireless
    - openwrt-firewall
    - openwrt-sqm
    - openwrt-dnsmasq
    - openwrt-ddns
